# Generated by Django 3.1.6 on 2021-03-04 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('sentby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentby', to=settings.AUTH_USER_MODEL)),
                ('sentto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CommingMessages',
        ),
    ]
